/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prenotazionegitarenzettibraganti;

import java.util.ArrayList;

/**
 *
 * @author renzetti.alessandro
 */
public class frmPrenotazione extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrenotazione.class.getName());

    /**
     * Creates new form frmPrenotazione
     */
    public frmPrenotazione() {
        initComponents();
        aggiungiElementi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbGite = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMostra = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbGite.setBackground(new java.awt.Color(255, 255, 204));
        cmbGite.setForeground(new java.awt.Color(0, 51, 51));
        cmbGite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGiteActionPerformed(evt);
            }
        });

        tblMostra.setBackground(new java.awt.Color(255, 255, 204));
        tblMostra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblMostra.setForeground(new java.awt.Color(0, 51, 51));
        tblMostra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMostra);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\renzetti.alessandro\\Desktopl\\PrenotazioneGiteBragantiRenzetti\\PrenotazioneGitaRenzettiBraganti\\fotoLab1 (1) (1).jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbGite, 0, 227, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGiteActionPerformed
        mostraStudenti();
    }//GEN-LAST:event_cmbGiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrenotazione().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblMostra;
    // End of variables declaration//GEN-END:variables
    GestioneGita gg = new GestioneGita();
    private GestioneFile gf = new GestioneFile();
    Gita g = new Gita();

    public void aggiungiElementi() {
        // Rimuove il listener temporaneamente per evitare trigger durante il caricamento
        cmbGite.removeActionListener(cmbGite.getActionListeners()[0]);
        cmbGite.removeAllItems();
        ArrayList<Gita> lista = gf.leggiFileGita();
        for (Gita g : lista) {
            cmbGite.addItem(g.getNome());
        }
        // Riaggiunge il listener
        cmbGite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGiteActionPerformed(evt);
            }
        });
        // Mostra subito gli studenti della prima gita selezionata
        if (cmbGite.getItemCount() > 0) {
            mostraStudenti();
        }
    }

    public void mostraStudenti() {
    String nomeScelto = (String) cmbGite.getSelectedItem();
    if (nomeScelto == null) return;

    // Trova l'id della gita selezionata
    String idGita = "";
    for (Gita g : gf.leggiFileGita()) {
        if (g.getNome().equals(nomeScelto)) {
            idGita = g.getId();
            break;
        }
    }

    // Intestazioni colonne
    String[] colonne = {"Nome", "Cognome", "Classe", "id"};
    ArrayList<String> idStudenti = gf.leggiStudentiPerGita(idGita);

    // Riempie i dati
    String[][] dati = new String[idStudenti.size()][4];
    for (int i = 0; i < idStudenti.size(); i++) {
        Studente s = gf.cercaStudenteById(idStudenti.get(i));
        if (s != null) {
            dati[i][0] = s.getNome();
            dati[i][1] = s.getCognome();
            dati[i][2] = s.getClasse();
            dati[i][3] =s.getId();
        }
    }

    tblMostra.setModel(new javax.swing.table.DefaultTableModel(dati, colonne));
}
}
