/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prenotazionegitarenzettibraganti;

import java.util.ArrayList;

/**
 *
 * @author renzetti.alessandro
 */
public class frmPrenotazione extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrenotazione.class.getName());

    /**
     * Creates new form frmPrenotazione
     */
    public frmPrenotazione() {
        initComponents();
        aggiungiElementi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbGite = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxVisualizza = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbGite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGiteActionPerformed(evt);
            }
        });

        atxVisualizza.setColumns(20);
        atxVisualizza.setRows(5);
        jScrollPane1.setViewportView(atxVisualizza);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGiteActionPerformed
        mostraStudenti();
    }//GEN-LAST:event_cmbGiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrenotazione().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxVisualizza;
    private javax.swing.JComboBox<String> cmbGite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    GestioneGita gg = new GestioneGita();
    private GestioneFile gf = new GestioneFile();
    Gita g = new Gita();

    public void aggiungiElementi() {
        // Rimuove il listener temporaneamente per evitare trigger durante il caricamento
        cmbGite.removeActionListener(cmbGite.getActionListeners()[0]);
        cmbGite.removeAllItems();
        ArrayList<Gita> lista = gf.leggiFileGita();
        for (Gita g : lista) {
            cmbGite.addItem(g.getNome());
        }
        // Riaggiunge il listener
        cmbGite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGiteActionPerformed(evt);
            }
        });
        // Mostra subito gli studenti della prima gita selezionata
        if (cmbGite.getItemCount() > 0) {
            mostraStudenti();
        }
    }

    public void mostraStudenti() {
        String nomeScelto = (String) cmbGite.getSelectedItem();
        if (nomeScelto == null) {
            return;
        }

        // Trova l'id della gita selezionata dal file
        String idGita = "";
        ArrayList<Gita> listaGite = gf.leggiFileGita();
        for (Gita g : listaGite) {
            if (g.getNome().equals(nomeScelto)) {
                idGita = g.getId();
                break;
            }
        }

        // Leggi le combinazioni e cerca gli studenti
        ArrayList<String> idStudenti = gf.leggiStudentiPerGita(idGita);
        atxVisualizza.setText("");
        if (idStudenti.isEmpty()) {
            atxVisualizza.setText("Nessuno studente iscritto.");
            return;
        }
        for (String idS : idStudenti) {
            Studente s = gf.cercaStudenteById(idS);
            if (s != null) {
                atxVisualizza.append(s.toString()+"-"+idGita+"\n");
            }
        }
    }
}
